name: Build w64devkit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up build environment
      run: |
       sudo apt update
       sudo apt install -y build-essential wget curl git tar

    - name: Build w64devkit
      run: |
       git clone https://github.com/skeeto/w64devkit.git
       cd w64devkit
       docker build -t w64devkit
       docker run --rm w64devkit >w64devkit-x64.exe

    - name: Upload da stuff
      uses: actions/upload-artifact@v4
      with:
       name: w64devkit-binaries
       path: ./w64devkit/bin
       pattern: my-artifact-*
